spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - loadtestsnapshot
      path-mapping:
        loadtestsnapshot: loadtest-snapshot
  endpoint:
    health:
      show-details: always

image:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ap-northeast-2
    prefix: local
    profile-name: community-api-local

  cloud-front:
    base-url: ${CLOUD_FRONT_BASE_URL}
